name: CI - TestNG

on:
  push:
    branches: ['main']
  pull_request: 
    branches: ['main']
jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Set up java
        uses: actions/setup-java@v4 
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Clone and run API locally
        run: | 
          git clone https://github.com/keikaavousi/fake-store-api.git fakestore
          cd fakestore
          npm install
          nohup npm start & # start local API in background
          sleep 5 # wait a few seconds for server to start

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashfiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run TestNG tests
        run: mvn clean test -Dgroups="regression"

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-Reports
          path: target/surefire-reports/