name: CI - TestNG

on:
  push:
    branches: ['main']
  pull_request: 
    branches: ['main']
jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Set up java
        uses: actions/setup-java@v4 
        with:
          java-version: '21'
          distribution: 'temurin'
      

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashfiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Clone and run API locally and tests
        run: | 
          git clone https://github.com/keikaavousi/fake-store-api.git fakestore
          cd fakestore
          npm install
          npm start &
          sleep 8 # wait for the API to start
          cd ..
          mvn clean test -Dgroups="smoke,regression"
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-Reports
          path: target/surefire-reports/